### ISSUE TITLE
Development Enviroment Setup 

### ISSUE THREAD

**Issue by The-NinToaster** [UPEI-Android/virtual-wellness-project#4]
No checklist here because I trust you guys to use your own workflows, however we should probably have a few things in common

1. Support for Javascript and PHP (React/Vue & Laravel)
2. Common Access to our Database (I (@The-NinToaster ) will sort that out and update this issue) 
3. Potentially a javascript or php linter for good code quality (i will also look into that) 

If there is anything else you guys want to add, comment on this issue

**Comment by jamqu** [comment]
just trying to figure out how to link issues
